### ISSUE TITLE
Clash royale 

### ISSUE THREAD

**Issue by HarryAllen1** [lutfisun/cty_seattle22#2]
@lutfisun

I've added a clash royale file in the repo root.

It contains a bunch of links.

More people should add their links

@PatLikesPizza

**Comment by PatLikesPizza** [comment]
HE HE HE HA

**Comment by HarryAllen1** [comment]
:(

**Comment by lutfisun** [comment]
heyyy

**Comment by lutfisun** [comment]
missed yall
